title: Andrew Nesbitt
email: andrew@nesbitt.io
description: >-
  Andrew is a software developer, based in Somerset, UK.
  He spends most of his days programming in Ruby, contributing to
  open source projects and organising local developer user groups.
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
